spring:
  application:
    name: user-center
  #session失效时间
  session:
    timeout: 86400
  #datasource config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: xxx
    username: xxx
    password: xxx
    hikari:
      max-lifetime: 30000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

server:
  port: 8080
  servlet:
    context-path: /api